[book]
authors = ["kijimad"]
language = "ja"
multilingual = false
src = "src"
title = "comemo"

[output.html]
additional-css = ["mdbook.css"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
